export interface CustomerContractItemAttributes {
  customerContractItemId: number,
  customerContractId: number,
  materialId: number,
  UOMCode: string,
  branchId: number,
  branchCode: string,
  branchName: string
  lineItemNumber: number
  quantity: number,
  numberOfDriver: number,
  helperIncluded: string,
  reportIncluded: string,
  UJPIncluded: string,
  fuel: string,
  channelType: string,
  tollAndParking: string,
  driverOrRider: string,
  crew?: string,
  coverageArea?: string,
  startDate: number,
  endDate?: number,
  isDedicated?: boolean,
  isWithDriver?: boolean,
  isActive: boolean,
  isNational?: boolean,
  status?: number,
  uniqueKey?: string,
  version: number,
  createdBy: number,
  createdAt: string,
  modifiedBy?: number,
  modifiedAt?: string,
  transactionId?: string,
  persistedDate?: string
  dataStoreTime?: string
  sapMssqlSinkTime?: string
};
