global using FluentValidation;
global using Mapster;
global using MediatR;
global using Microsoft.AspNetCore.Http;
global using Microsoft.EntityFrameworkCore;
global using Sera.Application.Constant;
global using Sera.Application.Function;
global using Sera.Application.Interface;
global using Sera.Common;
global using Sera.Common.Extension;
global using Sera.Common.Function;
global using Sera.Common.Interface.Message;
global using Sera.Common.Model.Entity;
global using Sera.Common.Model.Request;
global using Sera.Common.Model.Response;
global using System.ComponentModel;
global using System.Diagnostics.CodeAnalysis;
global using SQL = Sera.Entity.SQL;